export type Coord={r:number;c:number}
export type Intent={schema:1;kind:'move'|'kill'|'dipl'|'necro'|'resurrect';piece_id:number|string;to?:Coord;target_id?:number|string;displaced_to?:Coord;corpse_to?:Coord;nid_bonus_to?:Coord;reporter_mode?:'ortho'|'diag'}
export type ResolveResult={ok:true;state:any;event:any}|{ok:false;error:string}

type Piece={id:any;color:string;type:string;r:number;c:number;dead:boolean}
const LAB={r:4,c:4};const D8=[[0,1],[0,-1],[1,0],[-1,0],[1,1],[1,-1],[-1,1],[-1,-1]] as const;const ORTHO=[[0,1],[0,-1],[1,0],[-1,0]] as const;const DIAG=[[1,1],[1,-1],[-1,1],[-1,-1]] as const
const inB=(r:number,c:number)=>r>=0&&r<9&&c>=0&&c<9;const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));const same=(a:any,b:any)=>String(a)===String(b)

function rebuild(G:any){G.board=Array.from({length:9},()=>Array(9).fill(null));for(const color of Object.keys(G.players||{}))for(const p of G.players[color]?.pieces||[])if(inB(p.r,p.c)&&(!p.dead||G.board[p.r][p.c]==null))G.board[p.r][p.c]=p}
function pieces(G:any):Piece[]{const out:Piece[]=[];const seen=new Set<string>();for(const color of Object.keys(G.players||{}))for(const p of G.players[color]?.pieces||[]){const k=String(p.id);if(!seen.has(k)){seen.add(k);out.push(p)}}return out}
function byId(G:any,id:any){return pieces(G).find(p=>same(p.id,id))||null}
function cur(G:any){return G.order?.[G.idx]||null}
function move(G:any,p:Piece,r:number,c:number){if(inB(p.r,p.c)&&G.board[p.r][p.c]===p)G.board[p.r][p.c]=null;p.r=r;p.c=c;G.board[r][c]=p}
function remove(G:any,p:Piece){if(inB(p.r,p.c)&&G.board[p.r][p.c]===p)G.board[p.r][p.c]=null;p.r=-1;p.c=-1}
function place(G:any,p:Piece,r:number,c:number){p.r=r;p.c=c;G.board[r][c]=p}
function empty(G:any,d?:Coord){return !!d&&inB(d.r,d.c)&&!G.board[d.r][d.c]}
function hit(list:any[],d?:Coord){return !!d&&list.some(x=>x.r===d.r&&x.c===d.c)}

function linear(G:any,p:Piece){const moves:any[]=[],kills:any[]=[];for(const[dr,dc]of D8){let r=p.r+dr,c=p.c+dc;while(inB(r,c)){const t=G.board[r][c];if(!t){if(!(r===4&&c===4&&p.type!=='chef'))moves.push({r,c})}else if(t.dead)break;else{if(t.color!==p.color)kills.push({r,c,p:t});break}r+=dr;c+=dc}}return{moves,kills,diplT:[],necroT:[]}}
function militant(G:any,p:Piece){const moves:any[]=[],kills:any[]=[];for(const[dr,dc]of D8)for(let s=1;s<=2;s++){const r=p.r+dr*s,c=p.c+dc*s;if(!inB(r,c))break;const t=G.board[r][c];if(!t){if(r===4&&c===4)continue;moves.push({r,c})}else if(t.dead)break;else{if(t.color!==p.color&&!(t.type==='chef'&&r===4&&c===4))kills.push({r,c,p:t});break}}return{moves,kills,diplT:[],necroT:[]}}
function reporter(G:any,p:Piece){const moves:any[]=[];for(const[dr,dc]of D8){let r=p.r+dr,c=p.c+dc;while(inB(r,c)){if(G.board[r][c])break;if(!(r===4&&c===4))moves.push({r,c});r+=dr;c+=dc}}return{moves,kills:[],diplT:[],necroT:[]}}
function diplomat(G:any,p:Piece){const moves:any[]=[],diplT:any[]=[];for(const[dr,dc]of D8){let r=p.r+dr,c=p.c+dc;while(inB(r,c)){const t=G.board[r][c];if(!t){if(!(r===4&&c===4))moves.push({r,c})}else if(t.dead)break;else{if(t.color!==p.color)diplT.push({r,c,p:t});break}r+=dr;c+=dc}}return{moves,kills:[],diplT,necroT:[]}}
function necro(G:any,p:Piece){const moves:any[]=[],necroT:any[]=[];for(const[dr,dc]of D8){let r=p.r+dr,c=p.c+dc;while(inB(r,c)){const t=G.board[r][c];if(!t){if(!(r===4&&c===4))moves.push({r,c})}else if(t.dead){necroT.push({r,c,p:t});break}else break;r+=dr;c+=dc}}return{moves,kills:[],diplT:[],necroT}}
function baseActions(G:any,p:Piece){if(p.dead)return{moves:[],kills:[],diplT:[],necroT:[]};if(p.type==='militant')return militant(G,p);if(p.type==='reporter')return reporter(G,p);if(p.type==='diplomate')return diplomat(G,p);if(p.type==='necromobile')return necro(G,p);return linear(G,p)}
function actions(G:any,p:Piece){const sp=G.spPieces?.[p.id];if(sp?.type==='queen-move'){const b=baseActions(G,p),q=linear(G,p);return{...b,moves:[...b.moves,...q.moves.filter((m:any)=>!hit(b.moves,m))],kills:[...b.kills,...q.kills.filter((m:any)=>!b.kills.some((x:any)=>x.r===m.r&&x.c===m.c))]}}if(sp?.type==='resurrect')return{...baseActions(G,p),necroT:pieces(G).filter(x=>x.dead&&inB(x.r,x.c)).map(x=>({r:x.r,c:x.c,p:x})),resurrectMode:true};if(sp?.type==='free-move-corpse')return{...baseActions(G,p),moves:[],necroT:pieces(G).filter(x=>x.dead&&inB(x.r,x.c)).map(x=>({r:x.r,c:x.c,p:x})),freeMoveCorpse:true};return baseActions(G,p)}
function unsupportedSP(G:any,p:Piece,intent:Intent){const sp=G.spPieces?.[p.id];if(!sp)return null;if(sp.type==='double-kill')return'Double Kill n’est pas encore certifié par le noyau serveur.';if(sp.type==='area-kill'&&intent.kind==='move')return null;if(['queen-move','resurrect','free-move-corpse','invincible'].includes(sp.type))return null;return`Super Pouvoir non certifié online : ${sp.type}`}
function invincible(G:any,p:Piece){const sp=G.spPieces?.[p.id];return sp?.type==='invincible'&&Number(sp.turns)>0}
function tickInvincible(G:any,p:Piece){const sp=G.spPieces?.[p.id];if(sp?.type==='invincible'){sp.turns--;if(sp.turns<=0)delete G.spPieces[p.id]}}

function transferQueenLoss(G:any,loser:string,killer:string){const pl=G.players[loser],kp=G.players[killer];if(!pl?.alive)return;pl.alive=false;if(kp?.alive){for(const p of [...pl.pieces])if(!p.dead){p.color=killer;kp.pieces.push(p)};pl.pieces=pl.pieces.filter((p:Piece)=>p.dead)}else for(const p of pl.pieces)if(!p.dead)p.dead=true;G.order=G.order.filter((c:string)=>c!==loser);if(G.idx>=G.order.length)G.idx=0}
function killOne(G:any,attacker:Piece,victim:Piece,meta:any){victim.dead=true;meta.caps++;const queen=victim.type==='chef';remove(G,victim);if(queen)transferQueenLoss(G,victim.color,attacker.color);return!queen}
function reporterKill(G:any,p:Piece,mode:'ortho'|'diag'|'all',meta:any){const dirs=mode==='all'?D8:mode==='ortho'?ORTHO:DIAG;for(const[dr,dc]of dirs){const r=p.r+dr,c=p.c+dc;if(!inB(r,c))continue;const t=G.board[r][c];if(t&&!t.dead&&t.color!==p.color&&!invincible(G,t)){t.dead=true;meta.caps++;if(t.type==='chef')transferQueenLoss(G,t.color,p.color)}}}
function handleNid(G:any,p:Piece){if(p.type!=='chef')return;if(p.r===4&&p.c===4){if(G.labActive!==p.color){G.labActive=p.color;G.labExtra=-1}}else if(G.labActive===p.color){G.labActive=null;G.labExtra=-1}}
function finishTurn(G:any,meta:any){G.lastActor=cur(G);G.turn=Number(G.turn||0)+1;meta.turns++;const just=cur(G);if(G.labActive===just&&G.labExtra===-1){G.labExtra=1;return}if(G.labExtra===1&&G.labActive===just)G.labExtra=-1;if(G.order.length>1)G.idx=(G.idx+1)%G.order.length;else{G.over=true;G.winner=G.order[0]||null}}

function diff(before:any,after:any){const flat=(s:any)=>{const m=new Map<string,any>();for(const color of Object.keys(s?.G?.players||{}))for(const p of s.G.players[color]?.pieces||[])if(!m.has(String(p.id)))m.set(String(p.id),{id:p.id,color:p.color,type:p.type,r:p.r,c:p.c,dead:!!p.dead});return m};const b=flat(before),a=flat(after),out:any[]=[];for(const id of new Set([...b.keys(),...a.keys()])){const f=b.get(id),t=a.get(id);if(f&&t&&(f.r!==t.r||f.c!==t.c||f.dead!==t.dead||f.color!==t.color))out.push({kind:'piece_changed',id:t.id,color:t.color,type:t.type,from:{r:f.r,c:f.c,dead:f.dead,color:f.color},to:{r:t.r,c:t.c,dead:t.dead,color:t.color}})}return out}

export function resolveIntent(snapshot:any,intent:Intent,actorColor:string):ResolveResult{
  try{if(!snapshot?.G||intent?.schema!==1)return{ok:false,error:'Action ou snapshot invalide.'};const state=clone(snapshot),G=state.G;rebuild(G);if(cur(G)!==actorColor)return{ok:false,error:"Ce n'est pas votre tour."};const p=byId(G,intent.piece_id);if(!p||p.dead)return{ok:false,error:'Pièce introuvable.'};if(p.color!==actorColor)return{ok:false,error:'Cette pièce ne vous appartient pas.'};const spErr=unsupportedSP(G,p,intent);if(spErr)return{ok:false,error:spErr};const a:any=actions(G,p),meta={turns:Number(state.turns||0),caps:Number(state.caps||0)};const from={r:p.r,c:p.c}

    if(intent.kind==='move'){
      if(!hit(a.moves,intent.to))return{ok:false,error:'Déplacement illégal.'};move(G,p,intent.to!.r,intent.to!.c);tickInvincible(G,p);if(p.type==='reporter'){const sp=G.spPieces?.[p.id];if(sp?.type==='area-kill')reporterKill(G,p,'all',meta);else{const ortho=ORTHO.some(([dr,dc])=>{const t=G.board[p.r+dr]?.[p.c+dc];return t&&!t.dead&&t.color!==p.color});const diag=DIAG.some(([dr,dc])=>{const t=G.board[p.r+dr]?.[p.c+dc];return t&&!t.dead&&t.color!==p.color});if(ortho||diag){if(!intent.reporter_mode)return{ok:false,error:'Direction du Reporter requise.'};reporterKill(G,p,intent.reporter_mode,meta)}}}handleNid(G,p);finishTurn(G,meta)
    }else if(intent.kind==='kill'){
      const target=byId(G,intent.target_id);if(!target||target.dead)return{ok:false,error:'Cible invalide.'};if(!a.kills.some((x:any)=>same(x.p.id,target.id)))return{ok:false,error:'Capture illégale.'};if(invincible(G,target))return{ok:false,error:'Cette pièce est invincible.'};const killedOnNid=target.r===4&&target.c===4;move(G,p,target.r,target.c);tickInvincible(G,p);const corpse=killOne(G,p,target,meta);if(p.type==='assassin')place(G,target,from.r,from.c);else if(corpse){if(!empty(G,intent.corpse_to)||intent.corpse_to!.r===4&&intent.corpse_to!.c===4)return{ok:false,error:'Placement de dépouille invalide.'};place(G,target,intent.corpse_to!.r,intent.corpse_to!.c)}if(killedOnNid&&p.type!=='chef'){const bonus=baseActions(G,p).moves;if(!hit(bonus,intent.nid_bonus_to)||intent.nid_bonus_to!.r===4&&intent.nid_bonus_to!.c===4)return{ok:false,error:'Sortie du Nid requise.'};move(G,p,intent.nid_bonus_to!.r,intent.nid_bonus_to!.c)}handleNid(G,p);finishTurn(G,meta)
    }else if(intent.kind==='dipl'){
      const target=byId(G,intent.target_id);const h=a.diplT.find((x:any)=>target&&same(x.p.id,target.id));if(!target||target.dead||!h)return{ok:false,error:'Action du Diplomate illégale.'};if(!empty(G,intent.displaced_to))return{ok:false,error:'Destination déplacée invalide.'};remove(G,target);move(G,p,h.r,h.c);place(G,target,intent.displaced_to!.r,intent.displaced_to!.c);handleNid(G,p);finishTurn(G,meta)
    }else if(intent.kind==='necro'){
      const corpse=byId(G,intent.target_id);if(!corpse||!corpse.dead)return{ok:false,error:'Dépouille invalide.'};const free=G.spPieces?.[p.id]?.type==='free-move-corpse';const h=a.necroT.find((x:any)=>same(x.p.id,corpse.id));if(!free&&!h)return{ok:false,error:'Dépouille hors de portée.'};if(!empty(G,intent.corpse_to)||intent.corpse_to!.r===4&&intent.corpse_to!.c===4)return{ok:false,error:'Destination de dépouille invalide.'};remove(G,corpse);if(!free)move(G,p,h.r,h.c);place(G,corpse,intent.corpse_to!.r,intent.corpse_to!.c);handleNid(G,p);finishTurn(G,meta)
    }else if(intent.kind==='resurrect'){
      const corpse=byId(G,intent.target_id);if(G.spPieces?.[p.id]?.type!=='resurrect'||!corpse?.dead)return{ok:false,error:'Résurrection illégale.'};if(!intent.to||!inB(intent.to.r,intent.to.c)||G.board[intent.to.r][intent.to.c]&&!G.board[intent.to.r][intent.to.c].dead)return{ok:false,error:'Destination de résurrection invalide.'};const occupied=G.board[intent.to.r][intent.to.c];if(occupied?.dead)remove(G,occupied);remove(G,corpse);const old=corpse.color;corpse.color=p.color;corpse.dead=false;G.players[old].pieces=G.players[old].pieces.filter((x:Piece)=>!same(x.id,corpse.id));if(!G.players[p.color].pieces.some((x:Piece)=>same(x.id,corpse.id)))G.players[p.color].pieces.push(corpse);place(G,corpse,intent.to.r,intent.to.c);finishTurn(G,meta)
    }
    state.turns=meta.turns;state.caps=meta.caps;state.G.board=null;const event={schema:2,kind:'action_accepted',actor_color:actorColor,action:clone(intent),current_before:actorColor,current_after:cur(G),turn_before:Number(snapshot.G.turn||0),turn_after:Number(G.turn||0),changes:diff(snapshot,state)};return{ok:true,state,event}
  }catch(e){return{ok:false,error:e instanceof Error?e.message:'Erreur de résolution serveur.'}}
}
